# 检查更新设定
# 该选项用于插件判断是否要检查更新，若您不希望插件检查更新并提示您，可以选择关闭。
# 检查更新为异步操作，绝不会影响性能与使用体验。
check-update: true

properties:
  enable: true
  folder: "properties/"

configurations:
  "example-mariadb": # database id
    driver-type: mariadb
    url: 127.0.0.1 # 数据库地址
    port: 3306 # 数据库端口
    use-ssl: false # 是否使用SSL连接
    username: minecraft # 数据库用户名
    password: password #数据库连接密码
    database: minecraft #数据库名

